#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: The matching resource is not found.
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid.
                value:
                  code: FORMAT_NINO
  sandboxError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              sandboxError:
                description: The request did not match any available Sandbox data. Check that the request URI, API version and Gov-Test-Scenario are correct. This error will only be returned in the Sandbox environment.
                value:
                  code: SANDBOX_ERROR
  formatBusinessId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatBusinessId:
                description: The format of the supplied Business ID field is not valid.
                value:
                  code: FORMAT_BUSINESS_ID
  notFoundBusiness:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundbusiness:
                description: No business found for given NINO with given Business ID.
                value:
                  code: NO_BUSINESS_FOUND